import tomato from "../assets/vegetables/tomato.jpeg";
import carrot from "../assets/vegetables/carrot.jpeg";
import cucumber from "../assets/vegetables/cucumber.jpeg";
import onion from "../assets/vegetables/onion.jpeg";
import potato from "../assets/vegetables/potato.jpeg";
import pumpkin from "../assets/vegetables/pumpkin.jpeg";
import radish from "../assets/vegetables/radish.jpeg";
import spinach from "../assets/vegetables/spinach.jpeg";
import eggplant from "../assets/vegetables/eggplant.jpg";
import lettuce from "../assets/vegetables/lettuce.jpeg";
import cabbage from "../assets/vegetables/cabbage.jpeg";
import zucchini from "../assets/vegetables/zucchini.jpeg";
import broccoli from "../assets/vegetables/broccoli.jpeg";
import cauliflower from "../assets/vegetables/cauliflower.jpeg";
import garlic from "../assets/vegetables/garlic.jpeg";
import celery from "../assets/vegetables/celery.jpeg";
import leek from "../assets/vegetables/leek.jpeg";
import chard from "../assets/vegetables/chard.jpeg";
import chilipepper from "../assets/vegetables/chilipepper.jpeg";
import redbeet from "../assets/vegetables/redbeet.jpeg";
import fennel from "../assets/vegetables/fennel.jpeg";
import peapod from "../assets/vegetables/peapod.jpeg";
import redpepper from "../assets/vegetables/redpepper.jpeg";
import snappea from "../assets/vegetables/snappea.jpeg";
import sweetcorn from "../assets/vegetables/sweetcorn.jpeg";

const vegUnselected2 = [
  {
    name: "Tomato",
    src: tomato,
    id: 1,
    direct: "",
    prebreed:
      "From March to the beginning of April (for planting from the beginning to the end of May)",
    depth: "0.5 - 1 cm",
    temp: "18 - 22 °C",
    spacing: "approx. 100 x 50 cm",
    goodNeighbors: ["Carrot", "Onion", "Spinach"],
    badNeighbors: [
      "Potato",
      "Fennel",
      "Cabbage",
      "Broccoli",
      "Cauliflower",
      "Corn",
    ],
  },
  {
    name: "Carrot",
    src: carrot,
    id: 2,
    direct:
      "outdoors from March to the beginning of July at the latest, as bunched carrots until the end of July",
    prebreed: "",
    depth: "1.5 - 2.5 cm",
    temp: "",
    spacing: "30 - 50 x 2 - 3 cm",
    goodNeighbors: [
      "Tomato",
      "Onion",
      "Lettuce",
      "Radish",
      "Pea Pod",
      "Snap Pea",
    ],
    badNeighbors: [
      "Dill",
      "Parsley",
      "Potato",
      "Fennel",
      "Cucumber",
      "Cabbage",
      "Celery",
    ],
  },
  {
    name: "Cucumber",
    src: cucumber,
    id: 3,
    direct: "",
    prebreed: "from the beginning of May for planting from mid-MaySeeding",
    depth: "approx. 2 cm",
    temp: "23 - 26 °C",
    spacing: "approx. 100 x 50 cm",
    goodNeighbors: [
      "Corn",
      "Beans",
      "Radish",
      "Pea Pod",
      "Nasturtium",
      "Marigold",
    ],
    badNeighbors: [
      "Potato",
      "Aromatic Herbs",
      "Sage",
      "Tomato",
      "Pumpkin",
      "Onion",
      "Garlic",
    ],
  },
  {
    name: "Onion",
    src: onion,
    id: 4,
    direct: "from March to April",
    prebreed: "From February to March",
    depth: "1 - 2 cm",
    temp: "10 - 20 °C",
    spacing: "20 - 30 x 3 - 5 cm",
    goodNeighbors: [
      "Carrot",
      "Tomato",
      "Lettuce",
      "Pea Pod",
      "Beet",
      "Cabbage",
    ],
    badNeighbors: [
      "Pea Pod",
      "Beans",
      "Asparagus",
      "Cucumber",
      "Pumpkin",
      "Potato",
    ],
  },
  {
    name: "Potato",
    src: potato,
    id: 5,
    direct: "from April to May",
    prebreed: "from March to April",
    depth: "6 - 8 cm",
    temp: "8 - 12 °C",
    spacing: "30 - 35 x 60 - 70 cm",
    goodNeighbors: ["Beans", "Cabbage", "Corn", "Pea Pod", "Radish"],
    badNeighbors: ["Tomato", "Pumpkin", "Cucumber", "Carrot", "Onion"],
  },
  {
    name: "Pumpkin",
    src: pumpkin,
    id: 6,
    direct: "from May to June",
    prebreed: "from April to May",
    depth: "3 - 5 cm",
    temp: "18 - 25 °C",
    spacing: "100 x 100 cm",
    goodNeighbors: ["Corn", "Beans", "Radish", "Cucumber", "Pea Pod"],
    badNeighbors: ["Potato", "Aromatic Herbs", "Sage", "Tomato", "Onion"],
  },
  {
    name: "Radish",
    src: radish,
    id: 7,
    direct: "from April to September",
    prebreed: "",
    depth: "0.5 - 1 cm",
    temp: "5 - 25 °C",
    spacing: "2 - 3 cm",
    goodNeighbors: ["Carrot", "Lettuce", "Cucumber", "Pea Pod", "Spinach"],
    badNeighbors: [
      "Potato",
      "Fennel",
      "Cabbage",
      "Broccoli",
      "Cauliflower",
      "Corn",
    ],
  },
  {
    name: "Spinach",
    src: spinach,
    id: 8,
    direct: "from March to August",
    prebreed: "",
    depth: "1 - 2 cm",
    temp: "8 - 20 °C",
    spacing: "15 - 25 x 2 - 3 cm",
    goodNeighbors: ["Tomato", "Lettuce", "Radish", "Pea Pod", "Chard"],
    badNeighbors: [
      "Potato",
      "Fennel",
      "Cabbage",
      "Broccoli",
      "Cauliflower",
      "Corn",
    ],
  },
  {
    name: "Eggplant",
    src: eggplant,
    id: 10,
    direct: "from April to May",
    prebreed: "from March to April",
    depth: "2 - 3 cm",
    temp: "20 - 25 °C",
    spacing: "60 - 80 x 40 - 60 cm",
    goodNeighbors: [
      "Peppers",
      "Tomato",
      "Beans",
      "Lettuce",
      "Peas",
      "Spinach",
      "Thyme",
    ],
    badNeighbors: [
      "Potato",
      "Fennel",
      "Cabbage",
      "Broccoli",
      "Cauliflower",
      "Onion",
    ],
  },
  {
    name: "Lettuce",
    src: lettuce,
    id: 11,
    direct: "from March to October",
    prebreed: "",
    depth: "0.5 cm",
    temp: "8 - 15 °C",
    spacing: "20 - 30 x 3 - 5 cm",
    goodNeighbors: [
      "Carrot",
      "Radish",
      "Strawberry",
      "Cucumber",
      "Onion",
      "Chive",
      "Beet",
    ],
    badNeighbors: ["Cabbage", "Celery", "Parsley"],
  },
  {
    name: "Cabbage",
    src: cabbage,
    id: 12,
    direct: "from March to May",
    prebreed: "from February to March",
    depth: "0.5 cm",
    temp: "10 - 20 °C",
    spacing: "30 x 30 cm",
    goodNeighbors: ["Celery", "Onion", "Chamomile", "Dill", "Thyme"],
    badNeighbors: ["Tomato", "Beans", "Peas", "Strawberry", "Lettuce"],
  },
  {
    name: "Zucchini",
    src: zucchini,
    id: 9,
    direct: "from May to June",
    prebreed: "from April to May",
    depth: "2 - 3 cm",
    temp: "20 - 25 °C",
    spacing: "100 x 100 cm",
    goodNeighbors: [
      "Corn",
      "Beans",
      "Radish",
      "Cucumber",
      "Peas",
      "Marjoram",
      "Nasturtium",
    ],
    badNeighbors: [
      "Potato",
      "Aromatic Herbs",
      "Sage",
      "Tomato",
      "Pumpkin",
      "Onion",
    ],
  },
  {
    name: "Broccoli",
    src: broccoli,
    id: 13,
    direct: "from April to May",
    prebreed: "from March to April",
    depth: "0.5 cm",
    temp: "12 - 20 °C",
    spacing: "60 x 60 cm",
    goodNeighbors: ["Potato", "Nasturtium", "Dill", "Chamomile", "Thyme"],
    badNeighbors: ["Tomato", "Cabbage", "Strawberry", "Beans", "Peas"],
  },
  {
    name: "Cauliflower",
    src: cauliflower,
    id: 14,
    direct: "from April to May",
    prebreed: "from March to April",
    depth: "0.5 cm",
    temp: "12 - 20 °C",
    spacing: "60 x 60 cm",
    goodNeighbors: ["Celery", "Nasturtium", "Dill", "Chamomile", "Thyme"],
    badNeighbors: ["Tomato", "Cabbage", "Strawberry", "Beans", "Peas"],
  },
  {
    name: "Garlic",
    src: garlic,
    id: 16,
    direct: "from October to March",
    prebreed: "",
    depth: "3 - 5 cm",
    temp: "15 - 25 °C",
    spacing: "10 x 20 cm",
    goodNeighbors: [
      "Raspberry",
      "Strawberry",
      "Cherry Tree",
      "Peach Tree",
      "Apple Tree",
      "Pear Tree",
    ],
    badNeighbors: ["Beans", "Peas", "Cabbage", "Tomato", "Potato", "Marjoram"],
  },
  {
    name: "Chili Pepper",
    src: chilipepper,
    id: 15,
    direct: "from March to May",
    prebreed: "from February to March",
    depth: "0.5 cm",
    temp: "20 - 25 °C",
    spacing: "30 x 30 cm",
    goodNeighbors: [
      "Basil",
      "Onion",
      "Parsley",
      "Tomato",
      "Carrot",
      "Oregano",
      "Radish",
    ],
    badNeighbors: [
      "Fennel",
      "Beans",
      "Cabbage",
      "Cauliflower",
      "Brussels Sprouts",
      "Kohlrabi",
    ],
  },
  {
    name: "Celery",
    src: celery,
    id: 17,
    direct: "from April to May",
    prebreed: "from March to April",
    depth: "0.5 cm",
    temp: "15 - 20 °C",
    spacing: "30 x 30 cm",
    goodNeighbors: [
      "Cabbage",
      "Tomato",
      "Nasturtium",
      "Chives",
      "Dill",
      "Borage",
    ],
    badNeighbors: [
      "Carrot",
      "Beans",
      "Parsley",
      "Corn",
      "Fennel",
      "Chili Pepper",
    ],
  },
  {
    name: "Leek",
    src: leek,
    id: 18,
    direct: "from April to May",
    prebreed: "from February to March",
    depth: "1 cm",
    temp: "10 - 20 °C",
    spacing: "15 - 20 cm",
    goodNeighbors: [
      "Carrot",
      "Celery",
      "Onion",
      "Beet",
      "Cabbage",
      "Lettuce",
      "Radish",
    ],
    badNeighbors: ["Beans", "Peas", "Garlic", "Strawberry", "Tomato"],
  },
  {
    name: "Chard",
    src: chard,
    id: 19,
    direct: "from March to August",
    prebreed: "",
    depth: "1 - 2 cm",
    temp: "10 - 20 °C",
    spacing: "20 - 30 x 2 - 3 cm",
    goodNeighbors: [
      "Cabbage",
      "Broccoli",
      "Cauliflower",
      "Brussels Sprouts",
      "Kohlrabi",
      "Beet",
      "Radish",
    ],
    badNeighbors: ["Fennel", "Beans", "Onion", "Garlic", "Corn", "Sunflower"],
  },
  {
    name: "Red Beet",
    src: redbeet,
    id: 20,
    direct: "from March to July",
    prebreed: "from February to March",
    depth: "1 - 2 cm",
    temp: "10 - 20 °C",
    spacing: "3 - 5 cm",
    goodNeighbors: [
      "Lettuce",
      "Onion",
      "Sage",
      "Bush Bean",
      "Garlic",
      "Kohlrabi",
      "Chard",
    ],
    badNeighbors: [
      "Beans",
      "Field Radish",
      "Mustard Greens",
      "Parsley",
      "Soybean",
      "Tomato",
    ],
  },
  {
    name: "Fennel",
    src: fennel,
    id: 21,
    direct: "from April to May",
    prebreed: "from March to April",
    depth: "0.5 cm",
    temp: "10 - 20 °C",
    spacing: "20 - 30 x 3 - 5 cm",
    goodNeighbors: [
      "Lavender",
      "Cabbage",
      "Broccoli",
      "Cauliflower",
      "Brussels Sprouts",
      "Kohlrabi",
      "Caraway",
    ],
    badNeighbors: [
      "Tomato",
      "Beans",
      "Cucumber",
      "Dill",
      "Coriander",
      "Sage",
      "Carrot",
    ],
  },
  {
    name: "Pea Pod",
    src: peapod,
    id: 23,
    direct: "from March to May",
    prebreed: "from February to March",
    depth: "3 - 4 cm",
    temp: "8 - 15 °C",
    spacing: "3 - 4 cm",
    goodNeighbors: ["Carrot", "Onion", "Lettuce", "Spinach", "Radish"],
    badNeighbors: [
      "Potato",
      "Fennel",
      "Cucumber",
      "Tomato",
      "Pumpkin",
      "Garlic",
    ],
  },
  {
    name: "Red Pepper",
    src: redpepper,
    id: 24,
    direct: "from March to May",
    prebreed: "from February to March",
    depth: "0.5 cm",
    temp: "20 - 25 °C",
    spacing: "30 x 30 cm",
    goodNeighbors: ["Tomato", "Carrot", "Basil", "Parsley", "Lettuce"],
    badNeighbors: ["Potato", "Fennel", "Cucumber", "Onion", "Garlic"],
  },
  {
    name: "Snap Pea",
    src: snappea,
    id: 25,
    direct: "from March to May",
    prebreed: "from February to March",
    depth: "3 - 4 cm",
    temp: "8 - 15 °C",
    spacing: "3 - 4 cm",
    goodNeighbors: ["Carrot", "Onion", "Lettuce", "Spinach", "Radish"],
    badNeighbors: [
      "Potato",
      "Fennel",
      "Cucumber",
      "Tomato",
      "Pumpkin",
      "Garlic",
    ],
  },
  {
    name: "Sweet Corn",
    src: sweetcorn,
    id: 26,
    direct: "from April to May",
    prebreed: "from March to April",
    depth: "2 - 3 cm",
    temp: "15 - 20 °C",
    spacing: "20 - 25 cm",
    goodNeighbors: [
      "Potato",
      "Pumpkin",
      "Cucumber",
      "Melon",
      "Squash",
      "Pole Beans",
      "Peas",
    ],
    badNeighbors: [
      "Tomato",
      "Cabbage",
      "Cauliflower",
      "Brussels Sprouts",
      "Sunflower",
      "Cucumber",
      "Watermelon",
    ],
  },
];

// const vegUnselected = [
//   {
//     name: "Tomato",
//     src: tomato,
//     id: 1,
//     direct: "",
//     prebreed:
//       "From March to the beginning of April (for planting from the beginning to the end of May)",
//     depth: "0.5 - 1 cm",
//     temp: "18 - 22 °C",
//     spacing: "approx. 100 x 50 cm",
//   },
//   {
//     name: "Carrot",
//     src: carrot,
//     id: 2,
//     direct:
//       "outdoors from March to the beginning of July at the latest, as bunched carrots until the end of July",
//     prebreed: "",
//     depth: "1.5 - 2.5 cm",
//     temp: "",
//     spacing: "30 - 50 x 2 - 3 cm",
//   },
//   {
//     name: "Cucumber",
//     src: cucumber,
//     id: 3,
//     direct: "",
//     prebreed: "from the beginning of May for planting from mid-MaySeeding",
//     depth: "approx. 2 cm",
//     temp: "23 - 26 °C",
//     spacing: "approx. 100 x 50 cm",
//   },
//   {
//     name: "Onion",
//     src: onion,
//     id: 4,
//     direct: "from March to April",
//     prebreed: "From February to March",
//     depth: "1 - 2 cm",
//     temp: "10 - 20 °C",
//     spacing: "20 - 30 x 3 - 5 cm",
//   },
//   {
//     name: "Potato",
//     src: potato,
//     id: 5,
//     direct: "from April to May",
//     prebreed: "from March to April",
//     depth: "6 - 8 cm",
//     temp: "8 - 12 °C",
//     spacing: "30 - 35 x 60 - 70 cm",
//   },
//   {
//     name: "Pumpkin",
//     src: pumpkin,
//     id: 6,
//     direct: "from May to June",
//     prebreed: "from April to May",
//     depth: "3 - 5 cm",
//     temp: "18 - 25 °C",
//     spacing: "100 x 100 cm",
//   },
//   {
//     name: "Radish",
//     src: radish,
//     id: 7,
//     direct: "from April to September",
//     prebreed: "",
//     depth: "0.5 - 1 cm",
//     temp: "5 - 25 °C",
//     spacing: "2 - 3 cm",
//   },
//   {
//     name: "Spinach",
//     src: spinach,
//     id: 8,
//     direct: "from March to August",
//     prebreed: "",
//     depth: "1 - 2 cm",
//     temp: "8 - 20 °C",
//     spacing: "15 - 25 x 2 - 3 cm",
//   },
//   {
//     name: "Eggplant",
//     src: eggplant,
//     id: 10,
//     direct: "from April to May",
//     prebreed: "from March to April",
//     depth: "2 - 3 cm",
//     temp: "20 - 25 °C",
//     spacing: "60 - 80 x 40 - 60 cm",
//   },
//   {
//     name: "Lettuce",
//     src: lettuce,
//     id: 11,
//     direct: "from March to October",
//     prebreed: "",
//     depth: "0.5 cm",
//     temp: "8 - 15 °C",
//     spacing: "20 - 30 x 3 - 5 cm",
//   },
//   {
//     name: "Cabbage",
//     src: cabbage,
//     id: 12,
//     direct: "from March to May",
//     prebreed: "from February to March",
//     depth: "0.5 cm",
//     temp: "10 - 20 °C",
//     spacing: "30 x 30 cm",
//   },
//   {
//     name: "Zucchini",
//     src: zucchini,
//     id: 9,
//     direct: "from May to June",
//     prebreed: "from April to May",
//     depth: "2 - 3 cm",
//     temp: "20 - 25 °C",
//     spacing: "100 x 100 cm",
//   },
//   {
//     name: "Broccoli",
//     src: broccoli,
//     id: 13,
//     direct: "from April to May",
//     prebreed: "from March to April",
//     depth: "0.5 cm",
//     temp: "12 - 20 °C",
//     spacing: "60 x 60 cm",
//   },
//   {
//     name: "Cauliflower",
//     src: cauliflower,
//     id: 14,
//     direct: "from April to May",
//     prebreed: "from March to April",
//     depth: "0.5 cm",
//     temp: "12 - 20 °C",
//     spacing: "60 x 60 cm",
//   },
//   {
//     name: "Garlic",
//     src: garlic,
//     id: 16,
//     direct: "from October to March",
//     prebreed: "",
//     depth: "3 - 5 cm",
//     temp: "15 - 25 °C",
//     spacing: "10 x 20 cm",
//   },
//   {
//     name: "Chili Pepper",
//     src: chilipepper,
//     id: 15,
//     direct: "from March to May",
//     prebreed: "from February to March",
//     depth: "0.5 cm",
//     temp: "20 - 25 °C",
//     spacing: "30 x 30 cm",
//   },
//   {
//     name: "Celery",
//     src: celery,
//     id: 17,
//     direct: "from April to May",
//     prebreed: "from March to April",
//     depth: "0.5 cm",
//     temp: "15 - 20 °C",
//     spacing: "30 x 30 cm",
//   },
//   {
//     name: "Leek",
//     src: leek,
//     id: 18,
//     direct: "from April to May",
//     prebreed: "from February to March",
//     depth: "1 cm",
//     temp: "10 - 20 °C",
//     spacing: "15 - 20 cm",
//   },
//   {
//     name: "Chard",
//     src: chard,
//     id: 19,
//     direct: "from March to August",
//     prebreed: "",
//     depth: "1 - 2 cm",
//     temp: "10 - 20 °C",
//     spacing: "20 - 30 x 2 - 3 cm",
//   },
//   {
//     name: "Red Beet",
//     src: redbeet,
//     id: 20,
//     direct: "from March to July",
//     prebreed: "from February to March",
//     depth: "1 - 2 cm",
//     temp: "10 - 20 °C",
//     spacing: "3 - 5 cm",
//   },
//   {
//     name: "Fennel",
//     src: fennel,
//     id: 21,
//     direct: "from April to May",
//     prebreed: "from March to April",
//     depth: "0.5 cm",
//     temp: "10 - 20 °C",
//     spacing: "20 - 30 x 3 - 5 cm",
//   },
//   {
//     name: "Pea Pod",
//     src: peapod,
//     id: 23,
//     direct: "from March to May",
//     prebreed: "from February to March",
//     depth: "3 - 4 cm",
//     temp: "8 - 15 °C",
//     spacing: "3 - 4 cm",
//   },
//   {
//     name: "Red Pepper",
//     src: redpepper,
//     id: 24,
//     direct: "from March to May",
//     prebreed: "from February to March",
//     depth: "0.5 cm",
//     temp: "20 - 25 °C",
//     spacing: "30 x 30 cm",
//   },
//   {
//     name: "Snap Pea",
//     src: snappea,
//     id: 25,
//     direct: "from March to May",
//     prebreed: "from February to March",
//     depth: "3 - 4 cm",
//     temp: "8 - 15 °C",
//     spacing: "3 - 4 cm",
//   },
//   {
//     name: "Sweet Corn",
//     src: sweetcorn,
//     id: 26,
//     direct: "from April to May",
//     prebreed: "from March to April",
//     depth: "2 - 3 cm",
//     temp: "15 - 20 °C",
//     spacing: "20 - 25 cm",
//   },
// ];

export default vegUnselected;
